version: '3'

services:
    db:
        environment:
            MYSQL_DATABASE: db
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
        image: mysql:latest
        ports:
          - 3306:3306
    web:
        image: questapi:latest
        build: .
        command: python3 questAPI/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - fuseki
        environment:
          - SPARQL_ENDPOINT=http://fuseki:3030/
    fuseki:
      image: stain/jena-fuseki:3.4.0
      ports:
      - "3030:3030"

